name: 'Setup Git for Windows SDK'
description: 'Set up an environment to develop Git for Windows'
author: 'Johannes Schindelin'
branding:
  icon: fast-forward
  color: blue
inputs:
  flavor:
    required: true
    description: 'The subset (if any) of the SDK: minimal, makepkg-git, build-installers, or full'
    default: 'makepkg-git'
  architecture:
    required: true
    description: 'The architecture of the SDK: x86_64, i686 or aarch64. Note that "aarch64" only supports the "full" flavor for now.'
    default: 'x86_64'
  msys:
    required: false
    description: 'Whether to start in MSYS mode (defaults to false)'
    default: 'false'
  path:
    required: true
    description: 'Where to write the SDK files'
    default: ''
  cleanup:
    required: false
    description: 'Whether to clean up SDK files. This is only needed on self-hosted runners that are reused for multiple jobs.'
    default: 'false'
  verbose:
    required: true
    description: 'Whether to log files as they are extracted'
    default: '250'
  cache:
    required: false
    description: 'Use @actions/cache to accelerate this Action'
    default: 'auto'
  github-token:
    description: >
      Personal access token (PAT) used to call into GitHub's REST API.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
